package common

// GeogridProcCount ...
var GeogridProcCount = "84"

// MetgridProcCount ...
var MetgridProcCount = "84"

// WrfstepProcCount ...
var WrfstepProcCount = "132"

// WrfdaProcCount ...
var WrfdaProcCount = "42"

// RealProcCount ...
var RealProcCount = "42"
