package common

// GeogridProcCount ...
var GeogridProcCount = "84"

// MetgridProcCount ...
var MetgridProcCount = "84"

// WrfstepProcCount ...
var WrfstepProcCount = "84"

// WrfdaProcCount ...
var WrfdaProcCount = "50"

// RealProcCount ...
var RealProcCount = "36"
